server:
  port: 8083

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/prod_gea_db
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 8

  flyway:
    locations: classpath:db/migration,classpath:prod/db/migration